### ISSUE TITLE
Cross and dump fail at the very large time step of a timedep run

### ISSUE THREAD

**Issue by Chiil** [microhh/microhh#215] opened 2023-11-30 13:16 UTC
In the last rhs evaluation, the model fails in creating the crosses and dumps if there is no timedep info beyond the end step.
```
terminate called after throwing an instance of 'std::runtime_error'
  what():   Interpolation time is out of range; t1 = 64800.000000; current time is 64810.367831
```

Should we revert the timedep back to the state where it picks the value at the beginning / end or range if out of range, or should we find another solution?

**Comment by thijsheus** [comment] 2023-12-04 19:42
It feels a bit like a hack to do it that way, so at least it needs to be with an explicit check on whether begintime and endtime actually are within range. I can have a look in a bit.

**Comment by julietbravo** [comment] 2023-12-11 12:37
I'm having similar issues, it seems to be caused by lines like:
`const unsigned long itime_prev = ifactor * int(time/sampletime) * sampletime;`

**Comment by julietbravo** [comment] 2023-12-11 12:42
My MWE I'm testing things with, the commented out `Hmmmmmmmmmmmmmm` part is causing the issues.

```
#include <iostream>
#include <cstdlib>

int main()
{
    srand(time(NULL));

    const unsigned long ifactor = 1e9;
    const unsigned int sampletime = 100;
    const unsigned long isampletime = ifactor * sampletime + 0.5;

    double time = 0;
    unsigned long itime = 0;

    while (time < 7200)
    {
        double dt = double(rand()) / RAND_MAX;
        unsigned long idt = ifactor * dt + 0.5;

        // Time step limit.
        const unsigned long idtlim = isampletime - itime % isampletime;
        idt = std::min(idt, idtlim);
        dt  = static_cast<double>(idt) / ifactor;

        // Hmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm
        //const unsigned long itime_prev = ifactor * int(time/sampletime) * sampletime;
        //const unsigned long itime_next = itime_prev + sampletime*ifactor;

        unsigned long itime_prev = (itime / isampletime) * isampletime;
        unsigned long itime_next = itime_prev + isampletime;

        if (itime % isampletime == 0 && itime_prev != itime)
            std::cout << itime/double(ifactor) << " " << itime_prev/double(ifactor) << " " << itime_next/double(ifactor) << std::endl;

        itime += idt;
        time += dt;
    }

    return 0;
}
```

**Comment by julietbravo** [comment] 2024-02-20 10:23
Fixed by https://github.com/microhh/microhh/pull/229

**Closed by julietbravo** 2024-02-20 10:23 UTC
Labels: bug
