### ISSUE TITLE
Error saving restart files.

### ISSUE THREAD

**Issue by Ilovecodinghaha** [microhh/microhh#93] opened 2023-03-13 04:03 UTC
Hi there,

I installed microhh and openmpi and tried to run it. But I keep getting errors.
Can I get some help here, please? OR anyone can point out where the problem is.

I uesed anaconda to create input for LES. `python drycblles_input.py`
python version: python 3.9.13
netcdf4 version: 1.6.2

I ran python on windows, ran microhh on a Linux server.

I followed the [instruction](https://microhh.readthedocs.io/en/latest/getting_started/running_first_case.html):

1. After .`/microhh init drycblles`, I got `WARNING: [force][lslist] is not used! WARNING: [thermo][pbot] is not used!`
2. I tried ipython to plot it on jupyterlab/anaconda, both have the same error `KeyError: 'th'`.
3. I also run with mpi, after `mpiexec -n 4 ./microhh init drycblles` shows me `Saving "grid.0000000"...FAILED EXCEPTION: Error in grid`.

Please let me know what file you need to see the issue. The bulk output files after `python drycblles_input.py` is too large to attach.

Many thanks everyone!

**Comment by julietbravo** [comment] 2023-03-13 07:14
Hi,

1. Those warnings are harmless, and only tell that you have a setting in your `.ini` file which is not used. In this case, `lslist` is not used because `swls` is set to zero, and `pbot` is not used because the dry thermodynamics does not require the hydrostatic pressure.
2. It seems that the `drycblles_stats.py` script is not up-to-date with our NetCDF groups, I will fix that today.
3. One of the potential issues with `Saving "grid.0000000"...FAILED` errors is that `grid.0000000` already exists in your working directory (e.g. from a previous attempt to run the model). Is that the case? MicroHH is not allowed to overwrite existing files (`u.0000000`, `drycblles.default.0000000.nc`, et cetera), so you have to delete them manually.

If the model output (stdout/err) is too large to include, you can always put it on something like https://pastebin.com/

**Comment by julietbravo** [comment] 2023-03-13 08:14
The statistics script is fixed now: https://github.com/microhh/microhh/commit/08d9d9d2c9d3467118de4724297d76e5fda73d69

**Comment by julietbravo** [comment] 2023-03-13 19:47
Great! Have fun with the model ;-)

**Comment by julietbravo** [comment] 2023-03-14 06:50
> Hi team,
> I'm running moser180 now.
> python version: python 3.9.13, netcdf4 version: 1.6.2
> I ran both with mpi and without mpi (set npx = 2, npy = 2).
> It's running now, I'll update once I get the outputs.

> Hi team,
> Completed running, and trying to plot it.
> But after run moser180_stats.py, got errer:

    ~\MyPyFile\test_microhh\moser180_mpi\moser180_stats.py in <module>
         62 uw_rdstrMoser = Moseruw[:,4]
         63
    ---> 64 stats = nc.Dataset("moser180_default_0000000.nc","r")
         65 t  = stats.variables["time"] [start:end]
         66 z  = stats.variables["z"] [:]
    src\netCDF4\_netCDF4.pyx in netCDF4._netCDF4.Dataset.__init__()
    src\netCDF4\_netCDF4.pyx in netCDF4._netCDF4._ensure_nc_success()
    FileNotFoundError: [Errno 2] No such file or directory: b'moser180_default_0000000.nc'

> Is this because moser180_stats.py does not work well with the newest netcdf? The same as this issue Error saving restart files. https://github.com/microhh/microhh/issues/93?
> Thanks everyone.

I moved this from the other issue here, it doesn't seem to be related to that issue. `moser180` is a full DNS case, so pretty expensive. On how many MPI tasks do you run the case? About the error: our NetCDF statistics have been renamed from `casename_default_0000000.nc` to `casename.default.0000000.nc`, but it seems that not all plot scripts are updated. I will look at that.

**Comment by julietbravo** [comment] 2023-03-14 07:03
I would probably use ~24 or 32 cores at least, otherwise it will indeed take forever.

**Comment by julietbravo** [comment] 2023-03-15 19:36
@Chiil , the reference data is indeed missing from the repository. Do you still have it somewhere?

**Comment by julietbravo** [comment] 2023-03-15 19:42
Yes, that seems to be it! Didn't know it was still somewhere online...

**Comment by julietbravo** [comment] 2023-03-20 08:17
If the crash is indeed caused by a memory leak, it might be related to this NetCDF bug: https://github.com/Unidata/netcdf-c/issues/2626, from which we are also suffering. I just quickly tested `moser180`, which works fine if you switch the NetCDF backend from `NC_NETCDF4` to `NC_64BIT_OFFSET`.

    bart@eddy:~/meteo/models/microhh/cases/moser180$ git diff
    diff --git a/src/netcdf_interface.cxx b/src/netcdf_interface.cxx
    index 0c9e885f..5a254a23 100644
    --- a/src/netcdf_interface.cxx
    +++ b/src/netcdf_interface.cxx
    @@ -147,11 +147,11 @@ Netcdf_file::Netcdf_file(Master& master, const std::string& name, Netcdf_mode mo
         if (master.get_mpiid() == mpiid_to_write)
         {
             if (mode == Netcdf_mode::Create)
    -            nc_check_code = nc_create(name.c_str(), NC_NOCLOBBER | NC_NETCDF4, &ncid);
    +            nc_check_code = nc_create(name.c_str(), NC_NOCLOBBER | NC_64BIT_OFFSET, &ncid);
             else if (mode == Netcdf_mode::Write)
    -            nc_check_code = nc_open(name.c_str(), NC_WRITE | NC_NETCDF4, &ncid);
    +            nc_check_code = nc_open(name.c_str(), NC_WRITE | NC_64BIT_OFFSET, &ncid);
             else if (mode == Netcdf_mode::Read)
    -            nc_check_code = nc_open(name.c_str(), NC_NOWRITE | NC_NETCDF4, &ncid);
    +            nc_check_code = nc_open(name.c_str(), NC_NOWRITE | NC_64BIT_OFFSET, &ncid);
         }

**Comment by julietbravo** [comment] 2023-03-21 05:59
You can only restart from a `savetime`, in your case that seems to be `t=900 s`. Restarting the model is easy: set `starttime=900` in `[time]`, and run the model again with `./microhh run moser600` (or `mpiexec ...`). This will give you a new statistics file (`moser600.default.0000900.nc`), and you don't seem to have any cross-sections or other output, so there shouldn't be a need to manually delete any data or files.

**Comment by julietbravo** [comment] 2023-03-21 20:52
No, the `post` mode is only there to calculate statistic (e.g. `test_simulation.default.0000000.nc`) from existing restart files, without doing any time integration or other things in between. I.e., the code reads a restart file, calculates and saves the statistics, and moves on to the next restart file.

**Comment by julietbravo** [comment] 2023-03-30 10:39
Yes, that is annoying when restarting at a time earlier than where the previous run stopped. I have a Python script which can automatically merge two files and remove the overlapping times here: https://github.com/julietbravo/microhh/blob/develop_sb06/python/fix_overlapping_stats.py . It has not been tested very well, but it also does not overwrite/modify the original output files, so it is safe to test.

**Comment by julietbravo** [comment] 2023-03-31 06:46
This Python script calls some NCO routines, I have no idea if that works at all in a Windows environment. Can you try it on a Linux system which has NCO installed?

**Comment by julietbravo** [comment] 2023-04-04 06:40
Fixing the merged statistics with overlapping times would a few lines of Python code with xarray, but unfortunately xarray does not support NetCDF groups... If you do have access to NCO, you can do the steps from the Python script manually, with `ncks` to remove the overlapping times, and `ncrcat` to merge the statistics files. But that's always a bit of a pain in the ... because you manually need to find the indices to slice in the `ncks` step. 

Yes, typically it is sufficient to modify the `.ini` and `input.py` files. We have a Slack channel with MicroHH users, let me know if you want to be added there. That would make these kinds of discussions a bit easier.

**Comment by julietbravo** [comment] 2023-04-05 06:15
If you send me a message [here](https://www.wur.nl/en/contact_form.htm?contactpersonid=14843&contactpersonname=dr.ir.%20BJH%20%28Bart%29%20van%20Stratum&organisationname=Department%20of%20Environmental%20Sciences&organisationpart=Meteorology%20and%20Air%20Quality), then I'll add you to the channel.

**Closed** 2023-07-12 06:36 UTC
Labels: question
